# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - PY_VER: py37
            python-version: 3.7
          - PY_VER: py38
            python-version: 3.8
          - PY_VER: py39
            python-version: 3.9
          - PY_VER: py310
            python-version: '3.10'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install test dependencies
        run: pip install tox coveralls requests

      - name: Set env
        run: echo "USE_SAUCE_LABS=True" >> $GITHUB_ENV

      - name: Run lint
        run: tox -e flake8;

      - name: Run unit tests
        run: tox -e ${{matrix.PY_VER}}-stere;

      - uses: saucelabs/sauce-connect-action@v2.1.1
        if: ${{ matrix.PY_VER == 'py310' }}
        with:
          username: ${{secrets.SAUCE_USERNAME}}
          accessKey: ${{secrets.SAUCE_ACCESS_KEY}}
          tunnelIdentifier: github-action-tunnel

      - name: Run stere integration tests on Sauce Labs
        if: ${{ matrix.PY_VER == 'py310' }}
        env:
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
        run: |
          python scripts/upload_ios_app.py;
          tox -e ${{matrix.PY_VER}}-splinter -- --splinter-webdriver=remote --sauce-remote-url=http://${{secrets.SAUCE_USERNAME}}:${{secrets.SAUCE_ACCESS_KEY}}@ondemand.us-west-1.saucelabs.com/wd/hub;
          tox -e ${{matrix.PY_VER}}-appium -- --sauce-remote-url=http://${{secrets.SAUCE_USERNAME}}:${{secrets.SAUCE_ACCESS_KEY}}@ondemand.us-west-1.saucelabs.com/wd/hub;

      - name: "Upload coverage to Codecov"
        if: ${{ matrix.PY_VER == 'py310' }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
